blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/Abood204/AI_QUADROTOR_GNSS_RESEARCH/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
