data:
  run_dir: C:/Users/bedor/OneDrive/Documents/airsim-ai-quad - Copy/data/expert/centerline/run_20260204_155205
model:
  grayscale: true
  img_size:
  - 84
  - 84
  random_state: 42
  val_split: 0.2
output:
  model_dir: models
train:
  batch_size: 16
  clamp:
    r_z_rad:
    - -0.5
    - 0.5
    vx:
    - -0.6
    - 0.6
    vy:
    - -0.4
    - 0.4
    vz:
    - -0.2
    - 0.2
  early_stopping_patience: 20
  learning_rate: 0.0003
  num_epochs: 100
